[project]
name = "sql-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.2",
    "pydantic>=2.11.3",
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.40",
]
