services:
  sakila:
    image: mysql:8.0.42
    restart: always
    environment:
      MYSQL_DATABASE: 'sakila'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - sakila_vol:/var/lib/mysql


volumes:
  sakila_vol:
